# Cargo.toml

[package]
name = "rust_module"
version = "0.1.0"
edition = "2018"

[dependencies]
pyo3 = { version = "0.15", features = ["extension-module"] }
maturin = "0.13"

[lib]
crate-type = ["cdylib"]  # Needed for Python integration
